const actuDatas=[
    {title:"MOIS DE L’ARCHITECTURE ET DU PATRIMOINE",desc:"Les 15, 16 et 17 septembre, les Journées Européennes du Patrimoine inaugureront la 2e édition du Mois de l’architecture et du patrimoine. Durant un mois et jusqu’aux Journées nationales de l’Architecture (14-15 octobre), une riche programmation culturelle, artistique, scientifique mais aussi sensorielle vous sera proposée chaque semaine pour découvrir Beauvais et le Beauvaisis dans toutes leur diversité et leurs richesses. Du parcours d’art contemporain, aux démonstrations de savoir-faire en passant par des concerts, conférences mais aussi la découverte des travaux du quartier épiscopal et la Fête de la Science, laissez-vous séduire par un programme pour tous les goûts !",img:"./img/actus/actus1.jpg"},
    {title:"OCTOBRE ROSE",desc:"La campagne Octobre rose revient ! En partenariat avec la Ville de Beauvais, le Centre hospitalier Simone-Veil et plusieurs communes du Beauvaisis, l’association Perspectives contre le cancer propose un programme riche en actions de prévention.La campagne Octobre rose vise à renforcer la sensibilisation autour du dépistage précoce grâce à la mammographie de contrôle. Recommandée tous les 2 ans à partir de 50 ans (pour les femmes sans facteurs de risque particulier), elle est gratuite dans le cadre du dépistage organisé.Pour Tous, hommes compris !Chaque année, environ 500 hommes en France sont concernés par un cancer du sein." ,img:"./img/actus/actus2.jpg"},
    {title:"REUNION PUBLIQUE",desc:"Document d’urbanisme planifiant l’aménagement du territoire, le plan local d’urbanisme intercommunal valant habitat et mobilités de l’agglomération du Beauvaisis (PLUi-HM) est en cours actuel d’élaboration. Il couvrira à terme l’ensemble des 53 communes du territoire intercommunal.La phase du diagnostic s’est achevée, et les élus de l’Agglo ont ensuite travaillé sur une vision collective de l’avenir du territoire du Beauvaisis à l’horizon 2035. Un élément central a été établi, à savoir le projet d’aménagement et de développement durables (PADD).Ce dernier constituera le guide pour la suite de l’élaboration du PLUi-HM, mais aussi dans le cadre de ses modifications ultérieures (une fois le document adopté).",img:"./img/actus/actus3.jpg"},
    {title:"FETE DU CIDRE", desc:"Samedi 7 et dimanche 8 octobre, de 10h à 18h30, le Comité des fêtes de Milly-sur-Thérain organise la 32e Fête du cidre. Au programme de ce salon gastronomique et artisanal :Samedi : inauguration à 11h, restauration le midi, atelier de fabrication d'hôtel à insectes pour les enfants, dîner dansant sur réservation avec l'orchestre \"Sonia Eden Show\" et ses danseuses puis feu d'artifice à 20h30. Dimanche : restauration le midi puis, pendant l'après-midi, chanteurs de rue, exposition de cyclo-moteurs anciens, spectacle de side-car basket… Démonstrations de pressage de pommes tout le week-end Entrée gratuite. Renseignements & inscriptions par mail à comite.milly@orange.fr ou au 06 02 04 36 84.",img:"./img/actus/actus4.jpg"}
]
const mapDatas = {
    "picardSud": "Le Plateau Picard Sud de Beauvaisis est une région où l'agriculture et la campagne dominent le paysage. Ses vastes champs, ponctués de villages charmants, évoquent la tranquillité de la vie rurale. Le Plateau Picard Sud est connu pour son patrimoine historique, de la cathédrale Saint-Pierre de Beauvais aux églises médiévales disséminées dans la région. Ici, les activités de plein air sont une invitation à explorer la nature, que ce soit à travers la randonnée, le cyclisme ou la pêche. La cuisine locale offre des délices tels que le potjevleesch, tandis que les festivals d'art et les marchés locaux animent la région tout au long de l'année.",
    "picardNord": "Le Plateau Picard Nord de Beauvaisis est une région pittoresque située dans le nord de la France, dans le département de l'Oise, en région Hauts-de-France. Ce plateau vallonné offre un cadre naturel magnifique avec des champs verdoyants, des forêts pittoresques, et des collines douces. La région compte environ 60 000 habitants et est riche en histoire, avec des trésors comme la cathédrale Saint-Pierre de Beauvais. Les activités de plein air, telles que la randonnée, le cyclisme, la pêche et l'observation de la faune, sont courantes ici. La gastronomie locale est délicieuse, mettant en avant des plats picards traditionnels.",
    "therainAval": "La Vallée du Thérain Aval est un écrin de nature préservée, où les eaux du Thérain serpentent entre des collines boisées. Les villages de la vallée respirent l'authenticité et invitent à des balades paisibles. Cette région est un paradis pour les amoureux de la nature, offrant des sentiers de randonnée sinueux, des espaces de pique-nique au bord de la rivière, et une abondance de vie sauvage à observer. Les eaux calmes du Thérain Aval sont propices à la pêche. La Vallée du Thérain Aval est un endroit où l'on peut se ressourcer et se reconnecter avec la nature, loin du tumulte de la vie urbaine.",
    "bray": "La Boutonnière du Bray est une région de contrastes, où les vastes étendues de champs dorés rencontrent les collines boisées. Les villages typiques de la Boutonnière arborent des maisons à colombages et des ruelles étroites. C'est le lieu idéal pour découvrir la tradition picarde, avec sa cuisine délicieuse et son artisanat local. La région est également un havre de tranquillité, où les activités de plein air comme la randonnée et la découverte de la faune sont à l'honneur. La Boutonnière du Bray est une parenthèse enchantée dans laquelle le temps semble s'arrêter.",
    "beauvais": "Beauvais, la perle du Beauvaisis, est une ville riche en histoire et en culture. Au cœur de la ville se dresse la majestueuse cathédrale Saint-Pierre, qui impressionne par sa hauteur vertigineuse. Beauvais est un mélange harmonieux de tradition et de modernité, avec ses marchés animés, ses festivals d'art, et ses boutiques pittoresques. La cuisine locale est un délice pour les papilles, avec des spécialités telles que le ficelle picarde et le fromage Neufchâtel. La ville est un lieu de rencontre entre passé et présent, offrant une expérience culturelle inoubliable.",
    "therainAvelon": "La Thérain Avalon est une région où la rivière Thérain prend vie, avec ses rives bordées de verdure. La quiétude de la campagne règne ici, invitant à la détente. Les visiteurs peuvent suivre les méandres de la rivière, à pied ou à vélo, et découvrir les charmes cachés de la région. La Thérain Avalon est un lieu où le temps ralentit, offrant une échappée paisible dans un cadre naturel préservé, où les moments de sérénité sont légion."
};

const chiffresEconomiques={
    Etudiants:5000,
    Entreprises:600,
    Consommateurs:80,
    Structures:163

}
const agendaData=[
    {titre:"salon du livre de Hermes", date:"01/10/2023",desc:"Créé en novembre 2019, le salon du livre de Hermes tient sa 4e édition dimanche 1er octobre, de 10h à 18h, sur le thème « L’écriture sous toutes ses formes ». Il accueille pour l’occasion et dans un endroit atypique - l’église Saint-Vincent - une trentaine d’auteurs et un éditeur. L’édition 2023 a pour marraine Maître Murielle Bellier, avocate au barreau de Compiègne et auteure. Très sensible à l’impact des violences intrafamiliales sur les enfants, son témoignage rédigé à quatre mains « Ils ont assassiné mon père » ne laissera personne indifférent. La mairie accueillera le matin une conférence sur les graffitis de la préhistoire à nos jours et, l’après-midi un atelier d’écriture animé par l’auteure Anne-Claude Brumont. Les conseillers municipaux jeunes participeront également à un atelier peinture « Trashbirds » animé par Hélène Boissin, artiste peintre. Le salon se clôturera par la remise des prix de la « dictée adultes » organisée lors des Journées Européennes du Patrimoine à Hermes. Renseignements au 03 44 07 50 06 ou par mail à mairie@ville-hermes.fr"},
    {titre:"initiation à l'entrepreunariat",date :"03/10/2023", desc:"Pépite A2U accompagne les étudiants et les jeunes diplômés dans la création de leurs projets entrepreneuriaux. Divers événements sont organisés au Start lab tout au long de l’année universitaire : sensibilisation, formations, réseautaRattaché à l'Université de Picardie Jules Verne, Pépite A2U (*) agit comme le Pôle étudiant pour l'innovation et l'entrepreneuriat de l'alliance regroupant établissements d'enseignement supérieur, collectivités et acteurs de l'innovatSon objectif est de promouvoir la culture entrepreneuriale dans l'enseignement supérieuRendez-vous au Start LLes étudiants peuvent obtenir le Statut National d'Etudiant Entrepreneur (SNEE) du ministère de l’Enseignement supérieur et de la recherche, via Pépite A2U, grâce auquel ils accèdent à des événements, des concours et des réseaux pour développer leurs projets et remplacer leurs stages. En partenariat avec l'Agglomération du Beauvaisis, Pépite A2U organise des événements pour sensibiliser et former les étudiants entrepreneurs sur des sujets juridiques, financiers, de communication, de marketing, etc.Creator Game en octob Parmi les prochains événements, le \"Creator Game\" organisé mardi 3 octobre, dans l\’après-midi, au Start lab, permettra aux étudiants de s'initier à l'entrepreneuriat grâce à des jeux de société. Pour bénéficier du SNEE pendant l'année universitaire 2023-2024, les candidats peuvent également postuler sur la plateforme ministérielle en mettant en avant leur motivation à entreprenLes intéressés peuvent obtenir plus d'informations en contactant Valentin Fontaine, le chargé de mission Oise et Aisne, tous les mercredis de 9h à 17h au Start lab, situé 54 rue Tilloy à Beauvais."},
    {titre:"echange ouvert à tous",date:"10/10/2023",desc:"Document d’urbanisme planifiant l’aménagement du territoire, le plan local d’urbanisme intercommunal valant habitat et mobilités de l’agglomération du Beauvaisis (PLUi-HM) est en cours actuel d’élaboration. Il couvrira à terme l’ensemble des 53 communes du territoire intercommunalLa phase du diagnostic s’est achevée, et les élus de l’Agglo ont ensuite travaillé sur une vision collective de l’avenir du territoire du Beauvaisis à l’horizon 2035. Un élément central a été établi, à savoir le projet d’aménagement et de développement durables (PADD).Ce dernier constituera le guide pour la suite de l’élaboration du PLUi-HM, mais aussi dans le cadre de ses modifications ultérieures (une fois le document adopté).Afin de prendre connaissance des orientations du PADD, 6 nouvelles réunions publiques sont organisées en octobre 2023 :Le mardi 10 octobre 20Salle multifonctions de Rochy-ConDe 18h00 à 20h00"},
    {titre:"brocante-videgrenier",date:"27/08/2023",desc:"Dimanche 27 août, de 8h à 18h, la commune de Lafraye organise une brocante - vide-grenie L’inscription est possible jusqu'au 23 août, par téléphone au 03 44 80 47 31, le lundi de 8h30 à 11h30 et le mercredi de 8h30 à 18h30 6 € les 3 premiers mètres puis 5 € par tranche de 3 mètres supplémentaires La brocante aura lieu sur la place de Lafraye Une restauration sur place sera organisée par les membres du conseil municipal Plus d'infos sur le site officiel de la commune de Lafraye : https://lafraye.fr/fr/rb/662183/brocante-de-lafraye"},
    {titre:"prévention des déchets ménagers",date:"27/09/2023",desc:"La Communauté d’Agglomération du Beauvaisis prépare son Programme Local de Prévention des Déchets Ménagers et Assimilés (PLPDMA), 2024-2029.La prévention des déchets vise à réduire à la source la quantité de déchets produits. Le plan d’action autour de ce programme s’articule autour de 8 axes thématiques : l’éo-exemplarité, la sensibilisation du public, les instruments économiques, la lutte contre le gaspillage alimentaire, la sensibilisation à une consommation responsable, les biodéchets, l’augmentation de la durée de vie des produits et les déchets des entreprises.Avant son adoption par le Conseil communautaire de la CAB, le projet de PLPDMA doit être soumis à la consultation du public (Article R 541-41-24 du décret du 10 juin 2015 relatif aux PLPDMA)Dans le cadre de cette consultation, une réunion est organisée afin d’échanger avec les habitants de la CAB autour du projet :>>> Mercredi 27 septembre, 18h-19h30, au Cinéma CGR, salle 6 à Beauvais.À la suite de la réunion, de 19h30 à 20h, partageons ensemble un moment convivial autour d’un buffet dînatoire. Puis, regardons ensemble la projection du film TRASHED, réalisé par Candida Brady (OFFERT).Dès la fin de la consultation publique, la CAB rédigera une synthèse des observations du public et des modifications pourront être apportées au document."}
]  


export{actuDatas,mapDatas,chiffresEconomiques,agendaData};