const actuDatas=[
    {title:"MOIS DE L’ARCHITECTURE ET DU PATRIMOINE",desc:"Les 15, 16 et 17 septembre, les Journées Européennes du Patrimoine inaugureront la 2e édition du Mois de l’architecture et du patrimoine. Durant un mois et jusqu’aux Journées nationales de l’Architecture (14-15 octobre), une riche programmation culturelle, artistique, scientifique mais aussi sensorielle vous sera proposée chaque semaine pour découvrir Beauvais et le Beauvaisis dans toutes leur diversité et leurs richesses. Du parcours d’art contemporain, aux démonstrations de savoir-faire en passant par des concerts, conférences mais aussi la découverte des travaux du quartier épiscopal et la Fête de la Science, laissez-vous séduire par un programme pour tous les goûts !",img:"./img/actus/actus1.jpg"},
    {title:"OCTOBRE ROSE",desc:"La campagne Octobre rose revient ! En partenariat avec la Ville de Beauvais, le Centre hospitalier Simone-Veil et plusieurs communes du Beauvaisis, l’association Perspectives contre le cancer propose un programme riche en actions de prévention.La campagne Octobre rose vise à renforcer la sensibilisation autour du dépistage précoce grâce à la mammographie de contrôle. Recommandée tous les 2 ans à partir de 50 ans (pour les femmes sans facteurs de risque particulier), elle est gratuite dans le cadre du dépistage organisé.Pour Tous, hommes compris !Chaque année, environ 500 hommes en France sont concernés par un cancer du sein. C'est pourquoi la campagne Octobre rose vise également à sensibiliser la population masculine à l'importance de la prévention, du dépistage et de la vigilance vis-à-vis de cette maladie.Informer et rassemblerL'association Perspectives contre le cancer et ses partenaires organisent une série d'événements publics, gratuits et ouverts à tous dans le cadre de la campagne Octobre rose" ,img:"./img/actus/actus2.jpg"},
    {title:"REUNION PUBLIQUE",desc:"Document d’urbanisme planifiant l’aménagement du territoire, le plan local d’urbanisme intercommunal valant habitat et mobilités de l’agglomération du Beauvaisis (PLUi-HM) est en cours actuel d’élaboration. Il couvrira à terme l’ensemble des 53 communes du territoire intercommunal.La phase du diagnostic s’est achevée, et les élus de l’Agglo ont ensuite travaillé sur une vision collective de l’avenir du territoire du Beauvaisis à l’horizon 2035. Un élément central a été établi, à savoir le projet d’aménagement et de développement durables (PADD).Ce dernier constituera le guide pour la suite de l’élaboration du PLUi-HM, mais aussi dans le cadre de ses modifications ultérieures (une fois le document adopté).",img:"./img/actus/actus3.jpg"},
    {title:"FETE DU CIDRE", desc:"Samedi 7 et dimanche 8 octobre, de 10h à 18h30, le Comité des fêtes de Milly-sur-Thérain organise la 32e Fête du cidre. Au programme de ce salon gastronomique et artisanal :Samedi : inauguration à 11h, restauration le midi, atelier de fabrication d'hôtel à insectes pour les enfants, dîner dansant sur réservation avec l'orchestre \"Sonia Eden Show\" et ses danseuses puis feu d'artifice à 20h30. Dimanche : restauration le midi puis, pendant l'après-midi, chanteurs de rue, exposition de cyclo-moteurs anciens, spectacle de side-car basket… Démonstrations de pressage de pommes tout le week-end Entrée gratuite. Manifestation organisée par le Comité des fêtes avec le soutien la Communauté d’Agglomération du Beauvaisis, du Conseil départemental de l’Oise et de la mairie de Milly-sur-Thérain. Renseignements & inscriptions par mail à comite.milly@orange.fr ou au 06 02 04 36 84.",img:"./img/actus/actus4.jpg"},
    {title:"BEAUVAISIS 2035",desc:"Une étape importante a été engagée pour l’élaboration du plan local d’urbanisme intercommunal valant habitat et mobilités (PLUi-HM) du Beauvaisis : l’établissement progressif du projet d’aménagement et de développement durables (PADD). Depuis le début de l’année 2023, les élus de la Communauté d’Agglomération du Beauvaisis partagent des temps de travail divers (remplissage de cahiers d’intentions, ateliers en réunions sectorielles, séminaires des maires) pour croiser leurs regards sur différentes thématiques : l’armature territoriale, la démographie, les commerces et les services, les activités économiques et l’emploi, l’habitat, l’agriculture, les mobilités, l’environnement, le paysage, le patrimoine et le tourisme, la politique énergétique. Toute la matière recueillie va permettre de traduire les choix partagés par les 53 communes. Un scénario figurant le PADD sera alors décliné en objectifs et en actions, pour imaginer et construire l’avenir de l’Agglomération du Beauvaisis à l’horizon 2035.",img:"./img/actus/actus5.jpg"}
]
const mapDatas = {
    "picardSud": "Le Plateau Picard Sud de Beauvaisis est une région où l'agriculture et la campagne dominent le paysage. Ses vastes champs, ponctués de villages charmants, évoquent la tranquillité de la vie rurale. Le Plateau Picard Sud est connu pour son patrimoine historique, de la cathédrale Saint-Pierre de Beauvais aux églises médiévales disséminées dans la région. Ici, les activités de plein air sont une invitation à explorer la nature, que ce soit à travers la randonnée, le cyclisme ou la pêche. La cuisine locale offre des délices tels que le potjevleesch, tandis que les festivals d'art et les marchés locaux animent la région tout au long de l'année. La qualité de vie paisible attire ceux qui recherchent un équilibre entre rural et urbain.",
    "picardNord": "Le Plateau Picard Nord de Beauvaisis est une région pittoresque située dans le nord de la France, dans le département de l'Oise, en région Hauts-de-France. Ce plateau vallonné offre un cadre naturel magnifique avec des champs verdoyants, des forêts pittoresques, et des collines douces. La région compte environ 60 000 habitants et est riche en histoire, avec des trésors comme la cathédrale Saint-Pierre de Beauvais. Les activités de plein air, telles que la randonnée, le cyclisme, la pêche et l'observation de la faune, sont courantes ici. La gastronomie locale est délicieuse, mettant en avant des plats picards traditionnels. Le Plateau Picard Nord accueille tout au long de l'année des événements culturels et des festivals, offrant une expérience enrichissante. La qualité de vie y est excellente, avec ses villages charmants, sa tranquillité, et sa proximité avec la nature. C'est un endroit idéal pour vivre la culture picarde, se détendre dans un cadre paisible, et explorer l'histoire et la beauté naturelle de la région.",
    "therainAval": "La Vallée du Thérain Aval est un écrin de nature préservée, où les eaux du Thérain serpentent entre des collines boisées. Les villages de la vallée respirent l'authenticité et invitent à des balades paisibles. Cette région est un paradis pour les amoureux de la nature, offrant des sentiers de randonnée sinueux, des espaces de pique-nique au bord de la rivière, et une abondance de vie sauvage à observer. Les eaux calmes du Thérain Aval sont propices à la pêche. La Vallée du Thérain Aval est un endroit où l'on peut se ressourcer et se reconnecter avec la nature, loin du tumulte de la vie urbaine.",
    "bray": "La Boutonnière du Bray est une région de contrastes, où les vastes étendues de champs dorés rencontrent les collines boisées. Les villages typiques de la Boutonnière arborent des maisons à colombages et des ruelles étroites. C'est le lieu idéal pour découvrir la tradition picarde, avec sa cuisine délicieuse et son artisanat local. La région est également un havre de tranquillité, où les activités de plein air comme la randonnée et la découverte de la faune sont à l'honneur. La Boutonnière du Bray est une parenthèse enchantée dans laquelle le temps semble s'arrêter.",
    "beauvais": "Beauvais, la perle du Beauvaisis, est une ville riche en histoire et en culture. Au cœur de la ville se dresse la majestueuse cathédrale Saint-Pierre, qui impressionne par sa hauteur vertigineuse. Beauvais est un mélange harmonieux de tradition et de modernité, avec ses marchés animés, ses festivals d'art, et ses boutiques pittoresques. La cuisine locale est un délice pour les papilles, avec des spécialités telles que le ficelle picarde et le fromage Neufchâtel. La ville est un lieu de rencontre entre passé et présent, offrant une expérience culturelle inoubliable.",
    "therainAvelon": "La Thérain Avalon est une région où la rivière Thérain prend vie, avec ses rives bordées de verdure. La quiétude de la campagne règne ici, invitant à la détente. Les visiteurs peuvent suivre les méandres de la rivière, à pied ou à vélo, et découvrir les charmes cachés de la région. La Thérain Avalon est un lieu où le temps ralentit, offrant une échappée paisible dans un cadre naturel préservé, où les moments de sérénité sont légion."
};

const chiffresEconomiques={
    Etudiants:5000,
    Entreprises:600,
    Consommateurs:80,
    Structures:163

}
  
export{actuDatas,mapDatas,chiffresEconomiques};